<?php

return [
    'studio' => [
        'label' => 'Studio',
        'pieces' => [
            'Entrée',
            'Pièce principale',
            'Coin cuisine',
            'Salle de bain / WC',
        ],
    ],
    'f1' => [
        'label' => 'F1 / T1',
        'pieces' => [
            'Entrée',
            'Séjour',
            'Cuisine',
            'Salle de bain',
            'WC',
        ],
    ],
    'f2' => [
        'label' => 'F2 / T2',
        'pieces' => [
            'Entrée',
            'Séjour',
            'Cuisine',
            'Chambre',
            'Salle de bain',
            'WC',
        ],
    ],
    'f3' => [
        'label' => 'F3 / T3',
        'pieces' => [
            'Entrée',
            'Séjour',
            'Cuisine',
            'Chambre 1',
            'Chambre 2',
            'Salle de bain',
            'WC',
        ],
    ],
    'f4' => [
        'label' => 'F4 / T4',
        'pieces' => [
            'Entrée',
            'Séjour',
            'Cuisine',
            'Chambre 1',
            'Chambre 2',
            'Chambre 3',
            'Salle de bain',
            'WC',
        ],
    ],
    'f5' => [
        'label' => 'F5 / T5',
        'pieces' => [
            'Entrée',
            'Séjour',
            'Cuisine',
            'Chambre 1',
            'Chambre 2',
            'Chambre 3',
            'Chambre 4',
            'Salle de bain 1',
            'Salle de bain 2',
            'WC',
        ],
    ],
    'maison_t3' => [
        'label' => 'Maison T3',
        'pieces' => [
            'Entrée',
            'Séjour',
            'Cuisine',
            'Chambre 1',
            'Chambre 2',
            'Salle de bain',
            'WC',
            'Garage',
            'Jardin / Extérieur',
        ],
    ],
    'maison_t4' => [
        'label' => 'Maison T4',
        'pieces' => [
            'Entrée',
            'Séjour',
            'Cuisine',
            'Chambre 1',
            'Chambre 2',
            'Chambre 3',
            'Salle de bain',
            'WC',
            'Garage',
            'Jardin / Extérieur',
        ],
    ],
    'maison_t5' => [
        'label' => 'Maison T5',
        'pieces' => [
            'Entrée',
            'Séjour',
            'Cuisine',
            'Chambre 1',
            'Chambre 2',
            'Chambre 3',
            'Chambre 4',
            'Salle de bain 1',
            'Salle de bain 2',
            'WC 1',
            'WC 2',
            'Garage',
            'Jardin / Extérieur',
        ],
    ],
];